# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('name', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxWeight', models.FloatField()),
                ('time', models.FloatField()),
                ('cost', models.FloatField()),
                ('type', models.IntegerField(choices=[(0, 'sea'), (1, 'road'), (2, 'air')])),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Location')),
                ('leg', models.ManyToManyField(to='delivery.Leg')),
            ],
        ),
        migrations.AddField(
            model_name='leg',
            name='fromId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromId', to='delivery.Location'),
        ),
        migrations.AddField(
            model_name='leg',
            name='toId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toId', to='delivery.Location'),
        ),
    ]
