# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'launched'), (1, 'delivered')])),
                ('criteria', models.IntegerField(choices=[(1, 'cost'), (0, 'time')])),
                ('finishLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishLocation', to='delivery.Location')),
                ('itemList', models.ManyToManyField(to='delivery.Item')),
            ],
        ),
        migrations.RenameField(
            model_name='route',
            old_name='leg',
            new_name='legs',
        ),
        migrations.AddField(
            model_name='order',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Route'),
        ),
        migrations.AddField(
            model_name='order',
            name='startLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startLocation', to='delivery.Location'),
        ),
    ]
